// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PlayerCredential struct {
	ID         int64
	LoginToken pgtype.UUID
}
