// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUser = `-- name: AddUser :one
INSERT INTO player_credentials (login_token) VALUES ($1) RETURNING id
`

func (q *Queries) AddUser(ctx context.Context, loginToken pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, addUser, loginToken)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findUserByLoginToken = `-- name: FindUserByLoginToken :one
SELECT id FROM player_credentials WHERE login_token = $1
`

func (q *Queries) FindUserByLoginToken(ctx context.Context, loginToken pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, findUserByLoginToken, loginToken)
	var id int64
	err := row.Scan(&id)
	return id, err
}
