version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - dupl
    - errname
    - exhaustive
    - forcetypeassert
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace
    - wrapcheck
  settings:
    depguard:
      rules:
        main:
          allow:
            - github.com/gin-gonic/gin
            - github.com/gin-contrib/*
            - net/http
            - context
            - errors
            - fmt
            - time
          deny:
            - pkg: github.com/go-chi/chi
              desc: We standardize on Gin in this repo
    exhaustive:
      default-signifies-exhaustive: true
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G114
    revive:
      severity: warning
      rules:
        - name: blank-imports
        - name: early-return
        - name: errorf
        - name: exported
        - name: package-comments
        - name: context-as-argument
    wrapcheck:
      ignore-sigs:
        - errors.Join
        - fmt.Errorf
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
        path: '.*_test\.go$'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
