services:
  players:
    build:
      context: ./
      args:
        CGO_ENABLED: 0
        GO_SERVICE: players
        BUILD_TYPE: default
    ports:
      - "8080:8080"
  auth:
    build:
      context: ./
      args:
        CGO_ENABLED: 0
        GO_SERVICE: auth
        BUILD_TYPE: default
    ports:
      - "8081:8080"
    depends_on:
      - redis
      - postgres
  auth-migrate:
    build:
      context: ./
      args:
        CGO_ENABLED: 0
        GO_SERVICE: auth
        GO_CMD: ./services/auth/cmd/migrate/main.go
        BUILD_TYPE: default
    depends_on:
      - postgres
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
