service:
  version: 0.0.1
http:
  address: :8080
  shutdown-timeout: 5s
auth-service:
  player-lock-ttl: 30s
redis:
  server-address: redis:6379
token-factory:
  access-token-ttl: 15m
  refresh-token-ttl: 720h #30 days
player-storage-grpc:
  server-address: player-storage:9090
jwt:
  algorithm: HS256
  secret: secret
shutdown-timeout: 5s
