service:
  version: 0.0.1
http:
  address: :8080
  shutdown-timeout: 5s
  read-header-timeout: 3s
kafka:
  brokers:
    - kafka:9092
  topic: user-created
  group-id: players-service
shutdown-timeout: 5s
