name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run golangci-lint
        run: make golangci-lint
