name: SQLC

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate sqlc
        run: make gen_sqlc
      - name: Check for changes
        run: git diff --exit-code

